
# python compress_classifier.py ./data.cifar10/ -a resnet20_cifar --lr 0.1 -p 50 -b 128 -j 1
# --epochs 200 --compress=./config/resnet20_cifar_base_fp32.yaml --out-dir="logs/" --wd=0.0002 --vs=0

lr_schedulers:
  training_lr:
    class: MultiStepMultiGammaLR
    milestones: [80, 120, 160]
    gammas: [0.1, 0.1, 0.2]

policies:
    - lr_scheduler:
        instance_name: training_lr
      starting_epoch: 0
      ending_epoch: 200
      frequency: 1
